/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anode_arduino_jni_ArduinoCLINative */

#ifndef _Included_com_anode_arduino_jni_ArduinoCLINative
#define _Included_com_anode_arduino_jni_ArduinoCLINative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_anode_arduino_jni_ArduinoCLINative
 * Method:    compile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_anode_arduino_jni_ArduinoCLINative_compile
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_anode_arduino_jni_ArduinoCLINative
 * Method:    upload
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_anode_arduino_jni_ArduinoCLINative_upload
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_anode_arduino_jni_ArduinoCLINative
 * Method:    exec
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_anode_arduino_jni_ArduinoCLINative_exec
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
